server:
  port: 8080
  undertow:
    direct-buffers: true

spring:
  application:
    name: "awpaas-monitor"
  jackson:
    serialization:
      indent_output: true

management:
  security:
    enabled: false

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    time: 2018年04月06日 18:59:05
  describe: 服务监控中心
  home: /
  author: afterloe.L
  licensed: MIT Licensed

eureka:
  instance:
    preferIpAddress: false
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress:${random.value}}:${server.port}
    nonSecurePort: "${server.port:8080}"
    hostname: "${spring.application.name}"
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@awpaas-repository-1:8080/eureka/